/* global window */
/* Cocuna Clinic — mock data
   Anchors: Maria S. (the headline urgent case from the PDF) + 11 others.
   Mirrors the mother-app data shape for continuity (BP_READINGS, RESULT_PAYLOAD).
*/

const CLINIC = {
  name: 'Huntington-Hill Maternity Center',
  city: 'Pasadena, CA',
  cliniciansOnline: 4,
  rooms: ['L&D', 'Postpartum', 'NICU', 'Telehealth'],
};

const CLINICIAN_ME = {
  name: 'Dr. Sarah Patel',
  role: 'OB GYN',
  cred: 'MD, FACOG · Maternal-fetal',
  photo: 'doctor-patel.png',
  initials: 'SP',
};

const TRIAGE = {
  red:    { label: 'Urgent',    short: 'Red',    sla: 'Call now',         tone: 'red' },
  orange: { label: 'Same-day',  short: 'Orange', sla: 'Within 4 hours',   tone: 'orange' },
  yellow: { label: 'Review',    short: 'Yellow', sla: 'Within 72 hours',  tone: 'yellow' },
  green:  { label: 'Self-care', short: 'Green',  sla: 'Education sent',   tone: 'green' },
  gray:   { label: 'Insufficient', short: 'Gray', sla: 'Human review',    tone: 'gray' },
};

/* Maria's full Cocuna chat thread — the conversation a clinician can replay. */
const MARIA_THREAD = [
  { who: 'system', text: 'Maria opened Cocuna · 8:02 AM' },
  { who: 'hera',   text: 'Hello, Maria. Tell me what is happening. I\u2019m here to take care of you.' },
  { who: 'mother', text: 'I\u2019m 8 days postpartum. I have a bad headache and I\u2019m seeing spots. My blood pressure is 158 over 102.', meta: '8:02 AM' },
  { who: 'hera',   text: 'Thank you for telling me. I want to ask a few quick questions so we get this right.\n\nIs anyone with you at home right now?' },
  { who: 'mother', text: 'My mom is here. The baby is asleep.', meta: '8:03 AM' },
  { who: 'hera',   text: 'Good. Have you had any of these in the last hour?\n\n· chest pain or shortness of breath\n· pain in your upper right abdomen\n· swelling in your face or hands\n· trouble speaking, weakness on one side' },
  { who: 'mother', text: 'My hands feel a bit puffy. No chest pain.', meta: '8:04 AM' },
  { who: 'hera',   text: 'Have you taken any medication today?' },
  { who: 'mother', text: 'Just the iron pill from yesterday.', meta: '8:05 AM' },
  { who: 'hera',   text: 'I\u2019m going to ask your clinic to see you right away. Postpartum day 8 with these symptoms needs to be checked in person.\n\nWould you like me to call you a ride to Huntington Hospital ER?' },
  { who: 'mother', text: 'Yes please.', meta: '8:06 AM' },
  { who: 'hera',   text: 'Done. A ride is on the way (~6 minutes). Please don\u2019t drive yourself. Bring this conversation and your BP log.\n\nI\u2019ve also notified Dr. Patel.' },
  { who: 'system', text: 'Triage outcome — Red · Urgent escalation · clinic notified' },
];

/* Jane's mental-health thread */
const JANE_THREAD = [
  { who: 'system', text: 'Jane opened Cocuna · 11:08 PM (last night)' },
  { who: 'hera',   text: 'Hi Jane. How are you tonight?' },
  { who: 'mother', text: 'I cry every day. I feel detached from Lila. I can\u2019t sleep even when she sleeps.', meta: '11:09 PM' },
  { who: 'hera',   text: 'Thank you for telling me. That is hard. I want to understand a bit more, gently.\n\nHow long have you felt this way? More than two weeks?' },
  { who: 'mother', text: 'Almost three weeks now.', meta: '11:10 PM' },
  { who: 'hera',   text: 'In the last week, have you had any thoughts of hurting yourself or your baby?' },
  { who: 'mother', text: 'No. Just very tired. And sad.', meta: '11:11 PM' },
  { who: 'hera',   text: 'I hear you. What you\u2019re describing is common after a baby is born — and it is treatable.\n\nA few short questions, then we\u2019ll find someone for you to talk to.' },
  { who: 'system', text: 'EPDS screening administered · score 13 / 30 · moderate range' },
  { who: 'hera',   text: 'Would you like me to introduce you to Dr. Ana Ruiz, a perinatal psychologist? She is online and can talk within the hour.' },
  { who: 'mother', text: 'Yes. I think I need that.', meta: '11:18 PM' },
  { who: 'system', text: 'Triage outcome — Orange · Same-day behavioral review · soft flag to Dr. Patel' },
];

/* Emily's lactation thread */
const EMILY_THREAD = [
  { who: 'system', text: 'Emily opened Cocuna · Yesterday 3:14 PM' },
  { who: 'mother', text: 'Breastfeeding is so painful and I don\u2019t think my supply is enough. Lila is 4 weeks old.', meta: '3:14 PM' },
  { who: 'hera',   text: 'Let\u2019s look at this together. A few questions:\n\n· Is pain on one side, both sides, or only at latch?\n· Any redness, fever, or a hard spot?\n· How many wet diapers in 24 hours?' },
  { who: 'mother', text: 'Both sides, mostly at latch. 7 wets. No fever.', meta: '3:16 PM' },
  { who: 'hera',   text: 'Good news on diapers — supply sounds healthy. The pain pattern suggests latch can be adjusted.\n\nI\u2019d like to book a video with Naomi Okafor, IBCLC. She can usually see you within the day.' },
  { who: 'mother', text: 'Yes please.', meta: '3:17 PM' },
  { who: 'system', text: 'Triage outcome — Yellow · Lactation video consult booked' },
];

/* Roster — keyed by id; first 5 mirror the PDF table, then additions. */
const PATIENTS = [
  /* ===== Maria — the urgent case (headline) ===== */
  {
    id: 'maria',
    name: 'Maria S.',
    dob: '04 Apr 1992 · 33',
    photo: null,
    avatar: { initials: 'MS', tint: 'rose' },
    stage: 'Postpartum · day 8',
    delivery: 'Vaginal · 39w 2d · 2 Apr',
    triage: 'red',
    triageReason: 'BP 158/102 + headache + vision changes',
    flags: ['Postpartum d8', 'BP 158/102', 'Headache', 'Visual spots'],
    action: 'Call now / send to L&D',
    sla: 'Now',
    waitedMin: 4,
    care: { score: 78, level: 'Red', delta: '+34 since 7:14 AM' },
    careFactors: [
      { label: 'Maternal red flags (HTN + neuro)', pts: '+40' },
      { label: 'Vital deviation (BP delta > 30 mmHg)', pts: '+18' },
      { label: 'Days since visit (8)', pts: '+8' },
      { label: 'Baby red flags', pts: '0' },
      { label: 'Mental-health risk (EPDS 8)', pts: '+4' },
      { label: 'Uncertainty', pts: '+8' },
    ],
    riskFactors: ['Gestational hypertension', 'Primip'],
    mood: { epds: 8, note: 'No self-harm' },
    baby: { name: 'Lila', age: '8 days', feeding: 'Normal · 7 wet/day', stoolColor: 'Yellow', triage: 'green' },
    nextVisit: { when: 'Today 2:00 PM (booked just now)', kind: 'Postpartum BP check', visitType: 'In person' },
    threadKey: 'maria',
    suggestedAction: {
      title: 'Send to Labor & Delivery now',
      body: 'Ride dispatched. Bring chat & BP log. Notify L&D triage. Document escalation.',
      urgent: true,
    },
    aiSummary: 'Maria S., postpartum day 8 after vaginal delivery, history of gestational hypertension. Reports severe headache and visual spots today. Home BP 158/102 and 154/100, repeated. Hands mildly swollen. No chest pain, no upper-right abdominal pain. Baby Lila feeding normally, 7 wet diapers/day. Mood screen EPDS 8, no self-harm. Cocuna triage: Red urgent escalation due to postpartum hypertension red flags. Recommended action: same-day clinician contact and L&D evaluation for severe-range postpartum hypertension consistent with postpartum preeclampsia.',
    protocol: 'ACOG Severe Hypertension in Pregnancy · 2025 · AHA Maternal Review · 2025',
    medications: [
      { name: 'Prenatal multivitamin', dose: '1 tab daily',  since: 'pre-conception', class: 'supplement', flag: null },
      { name: 'Ferrous sulfate',       dose: '325 mg daily', since: '3rd trimester',   class: 'iron',       flag: null },
      { name: 'Ibuprofen',             dose: '200 mg PRN',   since: 'postpartum d2',  class: 'NSAID',      flag: 'Cautious in postpartum HTN' },
      { name: 'Acetaminophen',         dose: '500 mg PRN',   since: 'postpartum d2',  class: 'analgesic',  flag: null },
    ],
    allergies: ['Penicillin — rash'],
  },
  /* ===== Ana — orange ===== */
  {
    id: 'ana',
    name: 'Ana R.',
    dob: '15 Sep 1990 · 35',
    photo: null,
    avatar: { initials: 'AR', tint: 'lavender' },
    stage: 'Pregnant · 32 weeks',
    delivery: '—',
    triage: 'orange',
    triageReason: 'PHQ-9 high · insomnia · anxiety',
    flags: ['PHQ-9 14', 'Sleep < 4h', 'Anxiety 7d'],
    action: 'Same-day behavioral review',
    sla: 'Today',
    waitedMin: 18,
    care: { score: 54, level: 'Orange', delta: '+12 this week' },
    careFactors: [
      { label: 'Mental-health risk (PHQ-9 14)', pts: '+28' },
      { label: 'Sleep deprivation (< 4h, 5 nights)', pts: '+12' },
      { label: 'No self-harm reported', pts: '0' },
      { label: 'Vital deviation', pts: '+4' },
      { label: 'Maternal red flags', pts: '+6' },
      { label: 'Uncertainty', pts: '+4' },
    ],
    riskFactors: ['Anxiety dx pre-pregnancy'],
    mood: { epds: null, note: 'PHQ-9: 14 (moderate)' },
    baby: null,
    nextVisit: { when: 'Mon 11:00 AM', kind: '32w growth + behavioral', visitType: 'In person' },
    threadKey: 'ana',
    suggestedAction: { title: 'Route to Dr. Ana Ruiz today', body: 'Perinatal psych available 11am–6pm. Send brief summary + EPDS trend.' },
    aiSummary: 'Ana R., 32 weeks pregnant, history of anxiety prior to pregnancy. Reports worsening sleep (under 4 hours, 5 nights), anxiety, intrusive worry about labor. PHQ-9 administered: 14 (moderate). No suicidal ideation. EPDS trending up over 2 weeks. Cocuna triage: Orange — same-day behavioral review. Recommended action: brief CBT video consult with Dr. Ana Ruiz today; reassess at 32-week growth visit Monday.',
    protocol: 'ACOG Perinatal Mental Health · 2023',
    medications: [
      { name: 'Prenatal multivitamin', dose: '1 tab daily',  since: 'pre-conception', class: 'supplement', flag: null },
      { name: 'Sertraline',            dose: '50 mg daily',  since: 'pre-pregnancy',  class: 'SSRI',       flag: 'OK in pregnancy · monitor' },
    ],
    allergies: [],
  },
  /* ===== Emily — yellow ===== */
  {
    id: 'emily',
    name: 'Emily T.',
    dob: '02 Jan 1995 · 30',
    photo: null,
    avatar: { initials: 'ET', tint: 'mint' },
    stage: 'Postpartum · week 4',
    delivery: 'Vaginal · 38w 4d · 25 Mar',
    triage: 'yellow',
    triageReason: 'Breastfeeding pain + supply concern',
    flags: ['Pain bilateral', '7 wet/day', 'No fever'],
    action: 'Lactation video consult',
    sla: '24–72 hr',
    waitedMin: 41,
    care: { score: 32, level: 'Yellow', delta: 'steady' },
    careFactors: [
      { label: 'Maternal symptom (latch pain)', pts: '+10' },
      { label: 'Vitals normal', pts: '0' },
      { label: 'Baby intake normal', pts: '0' },
      { label: 'No fever / no redness', pts: '0' },
      { label: 'Mood normal', pts: '+4' },
      { label: 'Uncertainty', pts: '+8' },
    ],
    riskFactors: [],
    mood: { epds: 4, note: 'Normal' },
    baby: { name: 'Mae', age: '4 weeks', feeding: 'Bilateral pain at latch', stoolColor: 'Yellow', triage: 'green' },
    nextVisit: { when: 'Thu 4:00 PM', kind: 'Lactation video', visitType: 'Online' },
    threadKey: 'emily',
    suggestedAction: { title: 'Route to Naomi Okafor (IBCLC)', body: 'Async first, then 30-min video if pain persists.' },
    aiSummary: 'Emily T., postpartum week 4 after uncomplicated vaginal delivery. Reports bilateral nipple pain primarily at latch, concern about milk supply. Baby Mae 4 weeks, 7 wet diapers/day, yellow stool, weight gain on track per home log. No fever, no redness, no hard breast masses. Cocuna triage: Yellow — lactation video consult. Recommended action: route to Naomi Okafor (IBCLC); reassess after consult.',
    protocol: 'ABM Lactation Protocol #26 · 2024',
    medications: [
      { name: 'Prenatal multivitamin', dose: '1 tab daily', since: 'pre-conception', class: 'supplement', flag: null },
    ],
    allergies: [],
  },
  /* ===== Jordan — green ===== */
  {
    id: 'jordan',
    name: 'Jordan B.',
    dob: '—',
    photo: null,
    avatar: { initials: 'JB', tint: 'butter' },
    stage: 'Baby · 6 weeks',
    delivery: '—',
    triage: 'green',
    triageReason: 'Normal spit-up · feeding well',
    flags: ['7 wet/day', 'Weight +20%', 'No fever'],
    action: 'Education sent',
    sla: 'Closed',
    waitedMin: 0,
    care: { score: 9, level: 'Green', delta: 'down' },
    careFactors: [
      { label: 'Baby intake & output normal', pts: '0' },
      { label: 'Weight trend healthy', pts: '0' },
      { label: 'No fever', pts: '0' },
      { label: 'Mother screen normal', pts: '0' },
      { label: 'Uncertainty', pts: '+9' },
    ],
    riskFactors: [],
    mood: { epds: null, note: '—' },
    baby: { name: 'Jordan', age: '6 weeks', feeding: 'BF + bottle · spit-up after feeds', stoolColor: 'Yellow', triage: 'green' },
    nextVisit: { when: 'Fri 10:30 AM', kind: '2 month wellness', visitType: 'In person' },
    threadKey: null,
    suggestedAction: { title: 'Mark resolved · send education', body: 'Newborn spit-up handout sent. Re-flag if intake drops.' },
    aiSummary: 'Jordan B., 6 weeks old. Mother reports spit-up after most feeds. Intake and output normal, weight gain +20% from birth, no fever, no projectile vomiting, no blood. Cocuna triage: Green — self-care guidance. Reflux education handout sent. Re-flag if intake drops or vomit becomes projectile.',
    protocol: 'AAP Bright Futures · 2024',
  },
  /* ===== Sara — orange BP ===== */
  {
    id: 'sara',
    name: 'Sara K.',
    dob: '11 Jun 1988 · 37',
    photo: null,
    avatar: { initials: 'SK', tint: 'lavender' },
    stage: 'Postpartum · day 14',
    delivery: 'C-section · 38w 6d · 26 Mar',
    triage: 'orange',
    triageReason: 'BP 146/96 · headache mild',
    flags: ['BP 146/96', 'Headache mild', 'C-section d14'],
    action: 'Same-day video',
    sla: 'Today',
    waitedMin: 22,
    care: { score: 48, level: 'Orange', delta: '+9 today' },
    careFactors: [
      { label: 'Vital deviation', pts: '+18' },
      { label: 'Maternal symptom (headache)', pts: '+10' },
      { label: 'C-section incision normal', pts: '0' },
      { label: 'Mood screen 6', pts: '+6' },
      { label: 'Baby normal', pts: '0' },
      { label: 'Uncertainty', pts: '+14' },
    ],
    riskFactors: ['Prior C-section'],
    mood: { epds: 6, note: '—' },
    baby: { name: 'Noor', age: '14 days', feeding: 'BF · normal', stoolColor: 'Yellow', triage: 'green' },
    nextVisit: { when: '6w postpartum (in 4w)', kind: 'Postpartum check', visitType: 'In person' },
    threadKey: null,
    suggestedAction: { title: 'Same-day video w/ on-call OB', body: 'Repeat BP. If sustained > 150/100 → L&D.' },
    aiSummary: 'Sara K., postpartum day 14 after C-section. Reports home BP 146/96, mild bilateral headache responsive to acetaminophen. No vision changes, no abdominal pain. Incision clean. Baby Noor 14d, breastfeeding normally. Cocuna triage: Orange — same-day OB review. Recommend repeat BP under observation; escalate if sustained ≥150/100.',
    protocol: 'ACOG Postpartum Hypertension · 2025',
  },
  /* ===== Mei — yellow recovery ===== */
  {
    id: 'mei',
    name: 'Mei L.',
    dob: '24 Oct 1993 · 32',
    photo: null,
    avatar: { initials: 'ML', tint: 'mint' },
    stage: 'Postpartum · week 6',
    delivery: 'Vaginal · 40w 1d · 6 Mar',
    triage: 'yellow',
    triageReason: 'Persistent sleep deprivation · mild mood',
    flags: ['Sleep < 5h', 'Mood low 3d', 'No HTN'],
    action: 'PHQ-9 follow-up',
    sla: '72 hr',
    waitedMin: 95,
    care: { score: 28, level: 'Yellow', delta: 'steady' },
    careFactors: [
      { label: 'Mental-health risk (mild)', pts: '+10' },
      { label: 'Sleep deprivation', pts: '+8' },
      { label: 'No vital deviation', pts: '0' },
      { label: 'Baby normal', pts: '0' },
      { label: 'Uncertainty', pts: '+10' },
    ],
    riskFactors: [],
    mood: { epds: 9, note: 'Subclinical' },
    baby: { name: 'Theo', age: '6 weeks', feeding: 'Mixed · normal', stoolColor: 'Yellow', triage: 'green' },
    nextVisit: { when: '6w postpartum (Tue)', kind: 'Postpartum review', visitType: 'In person' },
    threadKey: null,
    suggestedAction: { title: 'Add EPDS to 6w visit', body: 'No urgent escalation. Education on postpartum mood and rest.' },
    aiSummary: 'Mei L., postpartum week 6. Reports cumulative sleep deprivation (under 5 hours per night × 3 days), mild low mood 3 days, no anhedonia, no self-harm. EPDS 9 (subclinical). Vitals normal. Baby Theo 6 weeks feeding well. Cocuna triage: Yellow — review at 6-week visit Tuesday with full EPDS.',
    protocol: 'ACOG Postpartum Care · 2018 (reaffirmed 2025)',
  },
  /* ===== Lila — green normal pregnancy question ===== */
  {
    id: 'lila',
    name: 'Lila G.',
    dob: '19 Mar 1996 · 29',
    photo: null,
    avatar: { initials: 'LG', tint: 'rose' },
    stage: 'Pregnant · 22 weeks',
    delivery: '—',
    triage: 'green',
    triageReason: 'Routine recovery question',
    flags: ['BP 118/74', 'No symptoms'],
    action: 'Education sent',
    sla: 'Closed',
    waitedMin: 0,
    care: { score: 8, level: 'Green', delta: 'down' },
    careFactors: [
      { label: 'Vitals normal', pts: '0' },
      { label: 'No symptoms', pts: '0' },
      { label: 'Mood screen normal', pts: '0' },
      { label: 'Uncertainty', pts: '+8' },
    ],
    riskFactors: [],
    mood: { epds: 3, note: '—' },
    baby: null,
    nextVisit: { when: '24w anatomy follow-up', kind: '24w visit', visitType: 'In person' },
    threadKey: null,
    suggestedAction: { title: 'No action · educational handout sent', body: 'Reflag if symptoms appear.' },
    aiSummary: 'Lila G., 22 weeks pregnant. Asked about normal Braxton-Hicks pattern. Vitals home BP 118/74. No headache, no vision changes, no fluid leak. Cocuna triage: Green — educational content sent on early contractions vs. true labor.',
    protocol: 'ACOG Antepartum · 2024',
  },
  /* ===== Jane — orange / mental health (the PDF mother-app persona) ===== */
  {
    id: 'jane',
    name: 'Jane W.',
    dob: '07 Feb 1991 · 34',
    photo: null,
    avatar: { initials: 'JW', tint: 'lavender' },
    stage: 'Postpartum · month 3',
    delivery: 'Vaginal · 39w 4d · 24 Feb',
    triage: 'orange',
    triageReason: 'EPDS 13 · sleep ↓ 3 weeks',
    flags: ['EPDS 13', 'Sleep ↓ 3w', 'No SI/HI'],
    action: 'Same-day perinatal psych',
    sla: 'Today',
    waitedMin: 6,
    care: { score: 51, level: 'Orange', delta: '+14 this week' },
    careFactors: [
      { label: 'Mental-health risk (EPDS 13)', pts: '+26' },
      { label: 'Sleep deprivation persistent', pts: '+10' },
      { label: 'Mood trend declining 7d', pts: '+8' },
      { label: 'No self-harm/harm ideation', pts: '0' },
      { label: 'Baby normal', pts: '0' },
      { label: 'Uncertainty', pts: '+7' },
    ],
    riskFactors: [],
    mood: { epds: 13, note: 'Moderate · no SI/HI' },
    baby: { name: 'Lila', age: '3 months', feeding: 'BF · normal', stoolColor: 'Yellow', triage: 'green' },
    nextVisit: { when: 'Thu 3:30 PM', kind: '3 month wellness', visitType: 'Online' },
    threadKey: 'jane',
    suggestedAction: { title: 'Route to Dr. Ana Ruiz', body: 'Soft flag to OB. Confirm safety check at next visit.' },
    aiSummary: 'Jane W., postpartum month 3. EPDS 13/30 (moderate). Symptoms: persistent low mood, sleep difficulty, detachment from baby for 3 weeks. No suicidal/homicidal ideation. Baby Lila 3 months, feeding well. Cocuna triage: Orange — same-day perinatal psychology consult booked with Dr. Ana Ruiz.',
    protocol: 'ACOG Perinatal Mental Health · 2023',
    medications: [
      { name: 'Prenatal multivitamin', dose: '1 tab daily', since: 'pre-conception', class: 'supplement', flag: null },
      { name: 'Iron + Vit C',          dose: '1 tab daily', since: 'postpartum',     class: 'supplement', flag: null },
    ],
    allergies: ['Latex'],
  },
  /* ===== Tessa — gray (insufficient) ===== */
  {
    id: 'tessa',
    name: 'Tessa O.',
    dob: '03 Aug 1994 · 31',
    photo: null,
    avatar: { initials: 'TO', tint: 'butter' },
    stage: 'Postpartum · day 21',
    delivery: 'Vaginal · 40w 0d · 19 Mar',
    triage: 'gray',
    triageReason: 'Vague symptom · model confidence low',
    flags: ['Conflicting answers', 'No vitals'],
    action: 'Human review needed',
    sla: 'Triage',
    waitedMin: 8,
    care: { score: 22, level: 'Gray', delta: '—' },
    careFactors: [
      { label: 'Symptom present (vague)', pts: '+4' },
      { label: 'No vitals on file', pts: '+8' },
      { label: 'Conflicting answers', pts: '+4' },
      { label: 'Model confidence low', pts: '+6' },
    ],
    riskFactors: [],
    mood: { epds: null, note: '—' },
    baby: { name: '—', age: '3 weeks', feeding: '—', stoolColor: '—', triage: 'gray' },
    nextVisit: { when: '—', kind: 'Awaiting triage', visitType: '—' },
    threadKey: null,
    suggestedAction: { title: 'Send to nurse for human triage', body: 'Ask for vitals + clarifying symptom location.' },
    aiSummary: 'Tessa O., postpartum day 21. Reports "not feeling right" without specific symptom. Conflicting answers when asked about pain location. No home vitals logged. Cocuna confidence low → Gray. Recommended action: nurse outreach for clarifying questions and home BP measurement before triage.',
    protocol: 'Cocuna Safety · Human review',
  },
  /* ===== Ben — baby growth ===== */
  {
    id: 'ben',
    name: 'Ben H.',
    dob: '—',
    photo: null,
    avatar: { initials: 'BH', tint: 'mint' },
    stage: 'Baby · 10 weeks',
    delivery: '—',
    triage: 'yellow',
    triageReason: 'Slow weight gain · feeding pattern',
    flags: ['+6% wk-on-wk', 'Cluster feeds'],
    action: 'Pedi nurse call',
    sla: '48 hr',
    waitedMin: 64,
    care: { score: 27, level: 'Yellow', delta: 'up' },
    careFactors: [
      { label: 'Baby growth slower than expected', pts: '+12' },
      { label: 'Feeding cluster pattern', pts: '+4' },
      { label: 'No fever / no other red flag', pts: '0' },
      { label: 'Mother screen normal', pts: '0' },
      { label: 'Uncertainty', pts: '+11' },
    ],
    riskFactors: [],
    mood: { epds: 4, note: '—' },
    baby: { name: 'Ben', age: '10 weeks', feeding: 'BF + cluster · normal output', stoolColor: 'Yellow', triage: 'yellow' },
    nextVisit: { when: 'Wed 11:00 AM', kind: 'Pedi nurse', visitType: 'Online' },
    threadKey: null,
    suggestedAction: { title: 'Pedi nurse Jane Kim · weighted feed', body: 'Weighted feed to check transfer.' },
    aiSummary: 'Ben H., 10 weeks. Mother reports cluster feeding past 5 days and weight gain slower than birth-track. Stool & wets normal. No fever. Cocuna triage: Yellow — pediatric nurse video to assess transfer; consider weighted feed.',
    protocol: 'AAP Bright Futures · 2024',
  },
  /* ===== Hana — pregnancy mid-care ===== */
  {
    id: 'hana',
    name: 'Hana M.',
    dob: '16 Dec 1989 · 36',
    photo: null,
    avatar: { initials: 'HM', tint: 'rose' },
    stage: 'Pregnant · 28 weeks',
    delivery: '—',
    triage: 'yellow',
    triageReason: 'Glucose tolerance pending · symptom diary',
    flags: ['BP 124/82', 'No symptoms', 'Awaiting GTT'],
    action: 'Routine review',
    sla: '72 hr',
    waitedMin: 120,
    care: { score: 19, level: 'Yellow', delta: 'steady' },
    careFactors: [
      { label: 'Risk factor (advanced maternal age)', pts: '+4' },
      { label: 'Awaiting GTT', pts: '+4' },
      { label: 'Vitals normal', pts: '0' },
      { label: 'Mood normal', pts: '0' },
      { label: 'Uncertainty', pts: '+11' },
    ],
    riskFactors: ['AMA'],
    mood: { epds: 2, note: '—' },
    baby: null,
    nextVisit: { when: '28w · Fri 10:00 AM', kind: '28w + GTT review', visitType: 'In person' },
    threadKey: null,
    suggestedAction: { title: 'Add GTT to Friday visit', body: 'Confirm fasting note.' },
    aiSummary: 'Hana M., 28 weeks. Asymptomatic. AMA. Glucose tolerance test pending. Home BP 124/82, mood normal. Cocuna triage: Yellow — routine 28-week visit on Friday with GTT.',
    protocol: 'ACOG Antepartum · 2024',
  },
];

const THREADS = {
  maria: MARIA_THREAD,
  jane:  JANE_THREAD,
  emily: EMILY_THREAD,
  ana: [
    { who: 'system', text: 'Ana opened Cocuna · last night 12:14 AM' },
    { who: 'mother', text: 'I can\u2019t sleep again. I\u2019m so anxious about the birth.', meta: '12:14 AM' },
    { who: 'hera',   text: 'I hear you. Let\u2019s talk through this calmly.\n\nHow many nights this week did you sleep less than four hours?' },
    { who: 'mother', text: 'Five.', meta: '12:16 AM' },
    { who: 'system', text: 'PHQ-9 administered · score 14 · moderate' },
    { who: 'hera',   text: 'Would you like me to find time with Dr. Ana Ruiz tomorrow? She specialises in perinatal anxiety.' },
    { who: 'mother', text: 'Yes.', meta: '12:21 AM' },
    { who: 'system', text: 'Triage outcome — Orange · same-day behavioral review' },
  ],
};

/* BP readings for Maria — drives the vitals chart. */
const MARIA_BP = [
  { date: 'Today, 8:02 AM',     sys: 158, dia: 102, triage: 'red' },
  { date: 'Yesterday, 9:14 PM', sys: 142, dia: 94,  triage: 'orange' },
  { date: 'Yesterday, 8:30 AM', sys: 138, dia: 89,  triage: 'orange' },
  { date: 'Mon, 9:05 PM',       sys: 134, dia: 86,  triage: 'yellow' },
  { date: 'Mon, 8:48 AM',       sys: 129, dia: 83,  triage: 'yellow' },
  { date: 'Sun, 9:20 PM',       sys: 126, dia: 81,  triage: 'green' },
  { date: 'Sun, 8:36 AM',       sys: 122, dia: 79,  triage: 'green' },
  { date: 'Sat, 9:00 PM',       sys: 124, dia: 80,  triage: 'green' },
  { date: 'Sat, 8:14 AM',       sys: 120, dia: 78,  triage: 'green' },
];

/* Maria timeline events (used in profile drawer) */
const MARIA_TIMELINE = [
  { when: 'Today · 8:06 AM', triage: 'red',    what: 'Cocuna escalation → ride to Huntington Hospital ER', detail: 'Notified Dr. Patel. L&D triage alerted.' },
  { when: 'Today · 8:02 AM', triage: 'red',    what: 'BP 158/102 · headache · visual spots', detail: 'Self-logged. Care Attention Score 78.' },
  { when: 'Yesterday · 9:14 PM', triage: 'orange', what: 'BP 142/94 · no symptoms', detail: 'Score 44. Educational handout sent.' },
  { when: 'Mon · 9:05 PM', triage: 'yellow', what: 'BP 134/86', detail: 'Watchful tracking enabled.' },
  { when: 'Sun · 8:36 AM', triage: 'green', what: 'BP 122/79 · mood 4/5', detail: 'Felt steady.' },
  { when: '2 Apr', triage: 'gray', what: 'Delivery · vaginal · 39w 2d', detail: 'Discharge day 2. Gestational HTN noted.' },
];

/* Analytics — pilot targets per the PDF */
const ANALYTICS = {
  green: 42,
  routedNonPhysician: 31,
  urgentSurfaced: 18,
  chartPrepBefore: 8,
  chartPrepAfter: 1.5,
  weekly: [
    { day: 'Mon', red: 2, orange: 6, yellow: 9,  green: 18, gray: 1 },
    { day: 'Tue', red: 3, orange: 8, yellow: 11, green: 22, gray: 2 },
    { day: 'Wed', red: 1, orange: 5, yellow: 13, green: 19, gray: 1 },
    { day: 'Thu', red: 4, orange: 7, yellow: 10, green: 24, gray: 1 },
    { day: 'Fri', red: 2, orange: 9, yellow: 8,  green: 21, gray: 3 },
    { day: 'Sat', red: 1, orange: 4, yellow: 6,  green: 14, gray: 1 },
    { day: 'Sun', red: 1, orange: 3, yellow: 7,  green: 11, gray: 2 },
  ],
};

window.COCUNA_DATA = {
  CLINIC, CLINICIAN_ME, TRIAGE,
  PATIENTS, THREADS,
  MARIA_BP, MARIA_TIMELINE,
  ANALYTICS,
};
